language: php

php:
  - 8.0

install:
- travis_retry composer install --no-interaction --no-suggest

before_script: 
- composer self-update
- composer install --no-interaction

script: 
- composer phpuint -- --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - main

cache:
  directories:
  - $HOME/.composer/cache  